//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        string verification(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        System.Threading.Tasks.Task<string> verificationAsync(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTeam", ReplyAction="http://tempuri.org/IService1/addTeamResponse")]
        string addTeam(
                    string url, 
                    string teamName, 
                    string college, 
                    string Conference, 
                    string qb1, 
                    string qb1last, 
                    string qb2first, 
                    string qb2last, 
                    string Number, 
                    string Number2, 
                    string qbr1, 
                    string qbr2, 
                    string h1, 
                    string h2, 
                    string wk1, 
                    string wk2, 
                    string wk3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTeam", ReplyAction="http://tempuri.org/IService1/addTeamResponse")]
        System.Threading.Tasks.Task<string> addTeamAsync(
                    string url, 
                    string teamName, 
                    string college, 
                    string Conference, 
                    string qb1, 
                    string qb1last, 
                    string qb2first, 
                    string qb2last, 
                    string Number, 
                    string Number2, 
                    string qbr1, 
                    string qbr2, 
                    string h1, 
                    string h2, 
                    string wk1, 
                    string wk2, 
                    string wk3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string verification(string xmlUrl, string xsdUrl) {
            return base.Channel.verification(xmlUrl, xsdUrl);
        }
        
        public System.Threading.Tasks.Task<string> verificationAsync(string xmlUrl, string xsdUrl) {
            return base.Channel.verificationAsync(xmlUrl, xsdUrl);
        }
        
        public string addTeam(
                    string url, 
                    string teamName, 
                    string college, 
                    string Conference, 
                    string qb1, 
                    string qb1last, 
                    string qb2first, 
                    string qb2last, 
                    string Number, 
                    string Number2, 
                    string qbr1, 
                    string qbr2, 
                    string h1, 
                    string h2, 
                    string wk1, 
                    string wk2, 
                    string wk3) {
            return base.Channel.addTeam(url, teamName, college, Conference, qb1, qb1last, qb2first, qb2last, Number, Number2, qbr1, qbr2, h1, h2, wk1, wk2, wk3);
        }
        
        public System.Threading.Tasks.Task<string> addTeamAsync(
                    string url, 
                    string teamName, 
                    string college, 
                    string Conference, 
                    string qb1, 
                    string qb1last, 
                    string qb2first, 
                    string qb2last, 
                    string Number, 
                    string Number2, 
                    string qbr1, 
                    string qbr2, 
                    string h1, 
                    string h2, 
                    string wk1, 
                    string wk2, 
                    string wk3) {
            return base.Channel.addTeamAsync(url, teamName, college, Conference, qb1, qb1last, qb2first, qb2last, Number, Number2, qbr1, qbr2, h1, h2, wk1, wk2, wk3);
        }
    }
}
